"""empty message

Revision ID: a84a61a45d47
Revises: 
Create Date: 2024-04-26 01:33:43.975185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a84a61a45d47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('password_hash')

    op.create_table('test',
    sa.Column('col1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('col2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('col3', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
